<div class="cat-block">
	<div class="block-title">
		<h3>Women</h3>
		<div class="cat-menu">
			<ul>
				<li><a href="">Donec lobortis</a></li>
				<li><a href="">pulvinar laoreet</a></li>
				<li><a href="">Nullam vehicula ligula</a></li>
				<li><a href="">Vestibulum vel neque</a></li>
				<li><a href="">Maecenas felis turpis</a></li>
			</ul>
		</div>
		<a class="more_cats" href="#">&nbsp;</a>
	</div><!--block-title-->

	<div class="cat-products">
	<?php
	$count = 0;
	foreach($products as $p):
		if($count%4==0) echo '<div class="clear"></div>';
	?>
		<div class="product-item <?php if($count%4==0) echo 'row-first';?>">
			<a class="product-img" href="<?php echo $this->url('product_view',array('id'=>$p->product_id));?>">
				<img src="<?php echo $this->basepath('/public/img/hinh_san_pham/').$p->image;?>"/>
			</a>
			<a class="product-name" href="<?php echo $this->url('product_view',array('id'=>$p->product_id));?>">
			<?php echo $p->product_name;?></a>
			<div class="product-price">
				<span class="price"><?php echo number_format($p->price,0,",",".")?> &#8363;</span>
			</div>
		</div><!--/product-item row-first-->
	<?php
	$count++;
	endforeach;
	?>
		<div class="clear"></div>
	</div><!--/cat-products-->
</div><!--/cat-block-->