<div class="featured-images">
	<img src="<?php echo $this->basepath('/public/img/') ?>File-1394178116.jpg"/>
</div><!--featured-image-->

<div class="cat-block">
	<div class="block-title">
		<h3>Women</h3>
		<div class="cat-menu">
			<ul>
				<li><a href="">Donec lobortis</a></li>
				<li><a href="">pulvinar laoreet</a></li>
				<li><a href="">Nullam vehicula ligula</a></li>
				<li><a href="">Vestibulum vel neque</a></li>
				<li><a href="">Maecenas felis turpis</a></li>
			</ul>
		</div>
		<a class="more_cats" href="#">&nbsp;</a>
	</div><!--block-title-->

	<div class="cat-products">
		<div class="product-item row-first">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item row-first-->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item row-first">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item row-first-->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="clear"></div>
	</div><!--/cat-products-->
</div><!--/cat-block-->

<div class="cat-block">
	<div class="block-title">
		<h3>Men</h3>
		<div class="cat-menu">
			<ul>
				<li><a href="">Donec lobortis</a></li>
				<li><a href="">pulvinar laoreet</a></li>
				<li><a href="">Nullam vehicula ligula</a></li>
				<li><a href="">Vestibulum vel neque</a></li>
				<li><a href="">Maecenas felis turpis</a></li>
			</ul>
		</div>
		<a class="more_cats" href="#">&nbsp;</a>
	</div><!--block-title-->

	<div class="cat-products">
		<div class="product-item row-first">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item row-first-->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item row-first">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item row-first-->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
				<span class="price old-price">250.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="product-item">
			<a class="product-img" href="">
				<img src="<?php echo $this->basepath('/public/img/') ?>no.jpg"/>
			</a>
			<a class="product-name" href="">Donec lobortis</a>
			<div class="product-price">
				<span class="price">160.000 &#8363;</span>
			</div>
		</div><!--/product-item -->
		<div class="clear"></div>
	</div><!--/cat-products-->
</div><!--/cat-block-->